### ISSUE TITLE
Will a non-soldered teensy be recognized as a keyboard?

### ISSUE THREAD

**Issue by Wesley-Chan** [benblazak/ergodox-firmware#69]
Hello.

I just want to make sure my teensy is good before soldering.

I flashed the blinky firmwares into it. It flashed differently. But after I flashed the ErgoDox [firmware](https://www.dropbox.com/sh/8bbol6fkvydmtmg/QLudrdEyc9) and plugged it in, neither Windows Device Manager nor `lsusb` in Linux lists it as a keyboard device.

I should note that my teensy is not soldered on the ErgoDox PCB yet.

Is ~~is~~ this (you can see how paranoid I was) normal or should I be concerned? What test should I do for verification?

Thank you.

**Comment by benblazak** [comment]
Take a look at the circuit diagram ([master](https://github.com/benblazak/ergodox-firmware/blob/master/src/keyboard/ergodox/circuit-diagram.svg), [partial-rewrite](https://github.com/benblazak/ergodox-firmware/blob/partial-rewrite/firmware/keyboard/ergodox/controller/circuit-diagram.svg)).  Minimally, the SCL and SDA pins (PD0 and PD1) need to have pull up resistors, otherwise, if I'm remembering correctly, the code that tries to initialize the MCP23018 (whether or not it's actually there) hangs.

**Comment by Wesley-Chan** [comment]
Thanks.

I removed the whiles in `teensy-2-0.c` and it worked! So relieved.
